
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp-server
  template:
    metadata:
      labels:
        app: ftp-server
    spec:
      containers:
      - name: ftp-server
        image: ftp-server:latest
        ports:
        - containerPort: 21
        - name: passive
          containerPort: 21100
          protocol: TCP


